_id: pUgyiLLEp1WQh7Ag
flags: {}
image: {}
name: System Settings
ownership:
  default: -1
sort: 500000
src: null
system: {}
text:
  content: >-
    <p>
      The Official Savage Worlds system for Foundry VTT offers a number of game
      settings you can configure to fine tune your game.
    </p>
    <h2>Card Sound</h2>
    <p>
      If enabled, Foundry plays a card-like sound effect when dealing initiative via
      its Combat Tracker.
    </p>
    <h2>Automatic Initiative</h2>
    <p>
      Progressing to the next round using the Combat Tracker automatically deals
      Action Cards if this is enabled. If a Joker was drawn, Foundry automatically
      shuffles the deck before dealing initiative for the new round.
    </p>
    <h2>Create Chat Message for Initiative</h2>
    <p>
      When Action Cards are drawn, Foundry will output the drawn Action Cards to the
      Chat if enabled.
    </p>
    <h2>Hide NPC Wild Cards</h2>
    <p>
      This option prevents players from being able to know whether or not an NPC is
      a Wild Card.
    </p>
    <h2>Automatically Link Wild Cards</h2>
    <p>
      Enabling this option automatically links NPC Wild Card tokens to their
      respective actors from which they are created.
    </p>
    <h2>Benny Notifications</h2>
    <p>
      When a GM rewards a Benny or when a character spends a Benny, Foundry displays
      a chat message respectively.
    </p>
    <h2>Card Deck to Use for Initiative</h2>
    <p>
      This setting allows you to select a custom card deck to use for initiative.
      For example, if you purchase a module containing a custom Action Deck or
      upload the
      <a
        rel="nofollow noreferrer noopener"
        href="https://www.peginc.com/store/vtt-deadlands-the-weird-west-action-deck/"
        target="_blank"
        >VTT Deadlands: the Weird West Action Deck</a
      >, you can select that deck to use for Initiative.
    </p>
    <h2>Ammunition Management</h2>
    <p>
      Automates ammunition usage. This is further controlled by weapon settings.
    </p>
    <ul>
      <li>
        <p>
          If both halves of the Shots counter are empty, the weapon won't use ammo.
          Otherwise, the system tries to match ammo options by name; if the ammo
          field is empty, it will suggest options from your inventory.
        </p>
      </li>
      <li>
        <p>
          If Reload Procedure is set to <strong>none</strong>, using any trait roll will
          directly pull from the linked ammunition, bypassing the Shots counter.
        </p>
        <ul>
          <li>
            <p>
              If the ammo is a <em>gear</em> type item, it will use the quantity.
            </p>
          </li>
          <li>
            <p>
              If the ammo is a <em>consumable</em> type item, it will use the
              charges.
            </p>
          </li>
        </ul>
      </li>
      <li>
        <p>
          If the Reload Procedure is set to <strong>self</strong>, using the weapon will 
          reduce its quantity and reset its shots counter whenever it runs out (e.g.
          for a throwing axe set max shots to 1, but for a can of bear spray that has 5
          uses per can set max shots to 5)
        </p>
      </li>
      <li>
        <p>
          If the Reload Procedure is set to <strong>single</strong>, each press of the
          Reload button will reduce the quantity of the gear item by 1 and increase
          the shots counter by 1.
        </p>
      </li>
      <li>
        <p>
          If the Reload Procedure is set to <strong>full</strong>, each press of the
          Reload button will attempt to completely refill the shots counter and
          reduce the gear item by the corresponding amount. If there isn't enough
          ammo left in your inventory, it will conduct a partial reload and reduce
          the quantity to zero.
        </p>
      </li>
      <li>
        <p>
          If the Reload Procedure is set to <strong>magazine</strong>, you reload by
          selecting specific consumables that both match the name listed in the Ammo
          field as well as are themselves set to the Magazine subtype. In addition,
          the magazine's max charges must be set to match the weapon's max shots. This
          lets you select from magazines from a dialog that shows their current shots
          remaining. This does not currently allow for ammo with special properties.
        </p>
      </li>
      <li>
        <p>
          If the Reload Procedure is set to <strong>battery</strong>, it works similar
          to a magazine but the consumable's max charges are always out of 100. A partially
          used battery has its charges set proportional to the shots used (e.g. if you
          discharge a battery after firing 10/20 shots, the battery will have 50/100 charges).
        </p>
      </li>
      <li>
        <p>
          If the Reload Procedure is set to <strong>Power Points</strong>, each press of
          the Reload button will reduce the linked power points by the "Power Points
          to Reload" value and refresh the shots counter to max.
        </p>
      </li>
    </ul>
  format: 1
  markdown: ''
title:
  level: 1
  show: true
type: text
video:
  controls: true
  volume: 0.5
_key: '!journal.pages!8uC7RTgJOg8SW4cf.pUgyiLLEp1WQh7Ag'
